### ISSUE TITLE
Proposed changes to the list, with explanations

### ISSUE THREAD

**Issue by weierophinney** [dignityinside/awesome-zf#1]
Hi! Thanks for tweeting your list; it's wonderful to see somebody doing this!

I have a few notes about a few of the links...

----

> Official Zend Framework repository https://github.com/zendframework/zendframework

This is misleading. The problem is that, since 2.5.0, the repository has been a _metapackage_, meaning there is no code in it, only a `composer.json` listing the various components as requirements. It may make more sense to link to the zendframework github organization (https://github.com/zendframework), which shows the many dozens of component repositories that make up the framework.

> User Guide https://framework.zend.com/manual/2.4/en/user-guide/overview.html
> 
> Programmer’s Reference Guide https://framework.zend.com/manual/2.4/en/index.html

These are out-of-date, and only refer to the 2.4 LTS version (which was released to allow long-term support for folks stuck on PHP 5.3). Reference https://docs.zendframework.com for both the user guide and reference guide, as it contains links to tutorials (user guide) as well as individual components (reference guide).

> Programmer’s Reference Guide https://zf2.readthedocs.io/en/latest

This was essentially just the test builds of the original ZF2 documentation reflected in the now obsolete LTS versions, as noted above; I'd remove this.

---

Thanks!

**Comment by dignityinside** [comment]
@weierophinney thank you for your feedback, done! :)
